{{- if .Values.persistence.hostPath.enabled }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ironic-pv-volume
  labels:
    type: local
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: default
  capacity:
    storage: {{ .Values.persistence.volume_capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ironic-pv-claim
  namespace: {{ .Values.namespace }}
spec:

  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.volume_capacity }}
