---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ironic.replicaCount }}
  selector:
    matchLabels:
      name: ironic
  template:
    metadata:
      labels:
        name: ironic
    spec:
      hostNetwork: true
      volumes:
        - name: ironic-storage
          persistentVolumeClaim:
           claimName: ironic-pv-claim
        {{- if .Values.ironic.config_override.dnsmasq }}
        - name: dnsmasq-entrypoint
          configMap:
            name: dnsmasq-entrypoint
            defaultMode: 0700
        - name: dnsmasq-config
          configMap:
            name: dnsmasq-config
            defaultMode: 0700
        {{- end }}
        {{- if .Values.ironic.config_override.httpd }}
        - name: httpd-entrypoint
          configMap:
            name: httpd-entrypoint
            defaultMode: 0700
        - name: httpd-config
          configMap:
            name: httpd-config
            defaultMode: 0700
        {{- end }}
        {{- if .Values.ironic.config_override.inspector_ipxe }}
        - name: inspector-ipxe-config
          configMap:
            name: inspector-ipxe-config
            defaultMode: 0644
        {{- end }}
        {{- if .Values.ironic.config_override.mariadb }}
        - name: mariadb-entrypoint
          configMap:
            name: mariadb-entrypoint
            defaultMode: 0700
        - name: mariadb-config
          configMap:
            name: mariadb-config
            defaultMode: 0700
        {{- end }}
        {{- if .Values.ironic.config_override.ironic }}
        - name: ironic-entrypoint
          configMap:
            name: ironic-entrypoint
            defaultMode: 0700
        - name: ironic-config
          configMap:
            name: ironic-config
            defaultMode: 0700
        {{- end }}
        {{- if .Values.ironic.config_override.inspector }}
        - name: inspector-entrypoint
          configMap:
            name: inspector-entrypoint
            defaultMode: 0700
        - name: inspector-config
          configMap:
            name: inspector-config
            defaultMode: 0700
        {{- end }}
        {{- if .Values.ironic.config_override.dualboot_ipxe }}
        - name: dualboot-ipxe-config
          configMap:
            name: dualboot-ipxe-config
            defaultMode: 0644
        {{- end }}
      {{- with .Values.ironic.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: dnsmasq
          image: {{ .Values.ironic.images.ironic_aio }}
          command: ["/bin/rundnsmasq"]
          securityContext:
            privileged: true
          env:
            - name: PROVISIONING_INTERFACE
              value: {{ .Values.ironic.configuration.provisioning_interface }}
            - name: HTTP_PORT
              value: {{ .Values.ironic.configuration.http_port | quote }}
            - name: DHCP_RANGE
              value: {{ .Values.ironic.configuration.dhcp_range }}
            - name: DNSMASQ_EXCEPT_INTERFACE
              value: {{ .Values.ironic.configuration.dnsmasq_except_interface }}
          volumeMounts:
              - mountPath: "/shared"
                name: ironic-storage
              {{- if .Values.ironic.config_override.dnsmasq }}
              - name: dnsmasq-entrypoint
                mountPath: /bin/rundnsmasq
                subPath: rundnsmasq.sh
              - name: dnsmasq-config
                mountPath: /cfg/dnsmasq.conf
                subPath: dnsmasq.conf
              {{- end }}
        - name: httpd
          image: {{ .Values.ironic.images.ironic_aio }}
          command: ["/bin/runhttpd"]
          securityContext:
            privileged: true
          env:
            - name: PROVISIONING_INTERFACE
              value: {{ .Values.ironic.configuration.provisioning_interface }}
            - name: HTTP_PORT
              value: {{ .Values.ironic.configuration.http_port | quote }}
          volumeMounts:
              - mountPath: "/shared"
                name: ironic-storage
              {{- if or .Values.ironic.config_override.httpd .Values.ironic.config_override.inspector_ipxe }}
              - name: httpd-entrypoint
                mountPath: /bin/runhttpd
                subPath: runhttpd.sh
              {{- end }}
              {{- if .Values.ironic.config_override.httpd }}
              - name: httpd-config
                mountPath: /cfg/httpd.conf
                subPath: httpd.conf
              {{- end }}
              {{- if .Values.ironic.config_override.inspector_ipxe }}
              - name: inspector-ipxe-config
                mountPath: /cfg/inspector.ipxe
                subPath: inspector.ipxe
              {{- end }}
              {{- if .Values.ironic.config_override.dualboot_ipxe }}
              - name: dualboot-ipxe-config
                mountPath: /tmp/dualboot.ipxe
                subPath: dualboot.ipxe
              {{- end }}
        - name: mariadb
          image: {{ .Values.ironic.images.ironic_aio }}
          command: ["/bin/runmariadb"]
          securityContext:
            privileged: true
          env:
            - name: MARIADB_PASSWORD
              value: {{ .Values.ironic.configuration.mariadb_password }}
            - name: PROVISIONING_INTERFACE
              value: {{ .Values.ironic.configuration.provisioning_interface }}
          volumeMounts:
            - mountPath: "/shared"
              name: ironic-storage
            - mountPath: "/var/lib/mysql"
              name: ironic-storage
              subPath: mysql
              {{- if .Values.ironic.config_override.mariadb }}
            - name: mariadb-entrypoint
              mountPath: /bin/runmariadb
              subPath: runmariadb.sh
            - name: mariadb-config
              mountPath: /cfg/my.cnf
              subPath: my.cnf
              {{- end }}
        - name: ironic
          image: {{ .Values.ironic.images.ironic_aio }}
          command: ["/bin/runironic"]
          securityContext:
            privileged: true
          env:
            - name: MARIADB_PASSWORD
              value: {{ .Values.ironic.configuration.mariadb_password }}
            - name: PROVISIONING_INTERFACE
              value: {{ .Values.ironic.configuration.provisioning_interface }}
            - name: HTTP_PORT
              value: {{ .Values.ironic.configuration.http_port | quote }}
          volumeMounts:
            - mountPath: "/shared"
              name: ironic-storage
            {{- if .Values.ironic.config_override.ironic }}
            - name: ironic-entrypoint
              mountPath: /bin/runironic
              subPath: runironic.sh
            - name: ironic-config
              mountPath: /cfg/ironic.conf
              subPath: ironic.conf
            {{- end }}
        - name: ironic-inspector
          image: {{ .Values.ironic.images.ironic_inspector }}
          command: ["/bin/runironic-inspector"]
          securityContext:
            privileged: true
          env:
            - name: PROVISIONING_INTERFACE
              value: {{ .Values.ironic.configuration.provisioning_interface }}
          volumeMounts:
            - mountPath: "/shared"
              name: ironic-storage
            {{- if .Values.ironic.config_override.inspector }}
            - name: inspector-entrypoint
              mountPath: /bin/runironic-inspector
              subPath: runironic-inspector.sh
            - name: inspector-config
              mountPath: /cfg/inspector.conf
              subPath: inspector.conf
            {{- end }}

