apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-baremetal-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metal3-baremetal-operator
  template:
    metadata:
      labels:
        name: metal3-baremetal-operator
    spec:
      serviceAccountName: metal3-baremetal-operator
      containers:
        - name: baremetal-operator
          image: {{ .Values.operator.image }}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - /baremetal-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "baremetal-operator"
            - name: DEPLOY_KERNEL_URL
              value: "http://{{- .Values.ironic.configuration.provisioning_ip }}/{{- .Values.operator.deploy_kernel_path }}"
            - name: DEPLOY_RAMDISK_URL
              value: "http://{{- .Values.ironic.configuration.provisioning_ip }}/{{- .Values.operator.deploy_ramdisk_path }}"
            - name: IRONIC_ENDPOINT
              value: "http://{{- .Values.ironic.configuration.provisioning_ip }}:6385/v1/"
            - name: IRONIC_INSPECTOR_ENDPOINT
              value: "http://{{- .Values.ironic.configuration.provisioning_ip }}:5050/v1/"
        # Temporary workaround to talk to an external Ironic process until Ironic is running in this pod.
        - name: ironic-proxy
          image: alpine/socat
          command: ["socat", "tcp-listen:6385,fork,reuseaddr", "tcp-connect:172.22.0.1:6385"]
          imagePullPolicy: Always
        - name: ironic-inspector-proxy
          image: alpine/socat
          command: ["socat", "tcp-listen:5050,fork,reuseaddr", "tcp-connect:172.22.0.1:5050"]
          imagePullPolicy: Always
